### ISSUE TITLE
Errors responses not always JSON

### ISSUE THREAD

**Issue by brettatoms** [keenlabs/KeenClient-Python#32] opened 2014-11-19 14:47 UTC
This line gives an error if the response isn't JSON:

https://github.com/keenlabs/KeenClient-Python/blob/master/keen/api.py#L156

For example when I submitted a filter where the property_value was a list with 1000 items the Keen API returns a 414 which causes crash on that line.  The crash gives no indication of what the error other than a JSON parse error.

**Comment by jchen123** [comment] 2016-03-16 23:18
Yep.  We get garbage like

Error from Keen API. Details:
 Message: The API did not respond with JSON, but: ""
Code: InvalidResponseFormat

**Comment by stroud109** [comment] 2016-05-05 21:57
Hey @jchen123, sorry that you're seeing an unhelpful error message. I haven't been able to reproduce the issue on my end yet. Can you let me know what version of the SDK are you using, and what kind of query you're trying to run?

**Comment by jchen123** [comment] 2016-05-05 22:06
Sure, we are using keen==0.3.21

keen.extraction(<property name>", property_names = '<one property name>', timeframe = <an absolute time frame of 1 day in length>, filters=<various filters>)

**Comment by stroud109** [comment] 2016-05-05 22:18
Thanks for the added context, @jchen123. How many property names and filters are you passing in? What timeframe are you using?

**Comment by jchen123** [comment] 2016-05-05 23:29
Count Error: 
    timeframe = {
        'start': '2016-01-27',
        'end': '2016-01-28'
    },
    filters = 1 equality filter

Count Unique Error:
    timeframe = {
        'start': '2016-04-24',
        'end': '2016-04-25'
    },
    filters = 1 equality filter

Extraction error
    timeframe = {
        'start': '2016-04-07',
        'end': '2016-04-08'
    },
1 equality filter, 1 exists filter

**Comment by stroud109** [comment] 2016-05-09 17:39
Thanks for the query info, @jchen123. Looks like you're experiencing a different issue than brettatoms (who has a [query optimization](https://keen.io/guides/query-performance/) issue). Are you still experiencing seemingly random errors without any message body? If so, could you let me know how often that's happening?

**Comment by jchen123** [comment] 2016-05-09 17:40
Upon further review it appears that it happens quite randomly throughout the day.  It also appears that it usually doesn't fail upon retry.  So we've just added retry logic to all of our querying.

**Comment by brettatoms** [comment] 2016-05-09 17:43
@stroud109 Just to be clear, my issue wasn't whether I could send a giant query or not but rather when an error is returned it is handled gracefully.  Basically the SDK expects JSON responses but JSON responses aren't always returned.

To be honest I haven't really checked if this issue is still a problem over the past few months.

**Comment by stroud109** [comment] 2016-05-10 20:23
Understood, brettatoms. We try to return `res.json()` and fall back on returning a formatted error that includes `res.text`. Unfortunately, there are sometimes errors with no message body. To account for those cases, I just added `res.status_code` to the formatted error. Hopefully exposing the status code will help troubleshoot future errors.

**Comment by josephwegner** [comment] 2017-01-19 18:58
Closing now, in hopes that the solution in #93 is sufficient. Feel free to respond back here if you are having further issues, and we can reopen.

**Closed by josephwegner** 2017-01-19 18:58 UTC
